---
- name: Main playbook to deploy db2 client
  hosts: "{{ envir }}:&dev"
  gather_facts: yes 
  become: true
  become_method: sudo
  vars_files:
    - var_files/main.yml
  roles: 
    - db2 
    - import_tasks: db2_client_install.yml
  tags: db2  


#   - name: Clone B on the remote
#   git:
#     repo: 'http://{{ git_user }}:{{ git_pass }}@somehost/B.git'
#     dest: /tmp/B

# # This copies the specified file from the remote to the current dir
# - name: Fetch yml from remote
#   fetch:
#     src: /tmp/B/Y.yml
#     dest: ./
#     flat: yes

# - name: Run Y
#   include_tasks: Y.yml